version: '3'

services:
  server:
    build: .
    entrypoint: ["go", "run", "server.go"]
    depends_on:
      - db
      - maildev
    environment:
      POSTGRESQL_URL: postgres://postgres:@db:5432/syncnow_development?sslmode=disable
    volumes:
      - .:/app:cached
      - go_modules:/golang:delegated
    ports:
      - 80:80
  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432

  maildev:
    image: djfarrelly/maildev
    ports:
      - 3025:80

volumes:
  go_modules:
  postgresql_data:
